name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant Permission
        run: chmod +x ./gradlew

      - name: Build Booking API
        run: ./gradlew build -x test



  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 416.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: interns-melinda

      - name: Build and Push Docker Image
        run: |
          gcloud config set project interns-melinda
          gcloud builds submit --tag gcr.io/interns-melinda/my-app .

      - name: Deploy to Google Cloud Run
        run: |
          gcloud config set project interns-melinda
          gcloud run deploy my-app --image gcr.io/interns-melinda/my-app --platform managed --region us-central1 --allow-unauthenticated
  

