name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant Permission
        run: chmod +x ./gradlew

      - name: Build Booking API
        run: ./gradlew build -x test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Build and Push Docker Image
        run: gcloud builds submit --tag ${{ env.IMAGE }} .
      - name: Deploy to Google Cloud Run
        run: gcloud run deploy my-app --image ${{ env.IMAGE }} --platform managed --region us-central1 --allow-unauthenticated
    env:
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app
