name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Booking API
        run: ./gradlew build -x



      - name: Deploy to Google Cloud Run
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project $PROJECT_ID
          gcloud builds submit --tag $IMAGE .
          gcloud run deploy my-app --image $IMAGE --platform managed --region us-central1 --allow-unauthenticated
